#!/bin/sh
# Git commit-msg hook (Go version)

HOOK_BIN="$(dirname "$0")/../../commit-msg-go"

if [ ! -x "$HOOK_BIN" ]; then
  echo "commit-msg-go binary not found or not executable: $HOOK_BIN" >&2
  exit 1
fi

exec "$HOOK_BIN" "$@"
